GOCMD=go
GOBUILD=$(GOCMD) build
GOCLEAN=$(GOCMD) clean
GOTEST=$(GOCMD) test

VENV=.venv
PYTHON=$(VENV)/bin/python3
PYVERS=3.13

all: build

build:
	$(GOBUILD) -v ./...

test: venv
	PATH="$(shell pwd)/$(VENV)/bin:$(PATH)" $(GOTEST) -v ./...

clean:
	$(GOCLEAN) ./...

fmts:
	gofmt -s -w .

vet:
	$(GOCMD) vet ./... | grep -v unkeyed; true

tidy:
	go mod tidy

mod-update:
	go get -u ./...
	go mod tidy

# --- Python / uv ---

venv:
	rm -r $(VENV)
	uv venv --seed -p $(PYVERS) $(VENV)
	uv pip install -p $(PYTHON) .

prereq: venv

clean-venv:
	rm -rf $(VENV)


# NOTE: MUST update version number here prior to running 'make release' and edit this file!
VERS=v0.4.11
PACKAGE=main
GIT_COMMIT=`git rev-parse --short HEAD`
VERS_DATE=`date -u +%Y-%m-%d\ %H:%M`
VERS_FILE=version.go

release:
	/bin/rm -f $(VERS_FILE)
	@echo "// WARNING: auto-generated by Makefile release target -- run 'make release' to update" > $(VERS_FILE)
	@echo "" >> $(VERS_FILE)
	@echo "package $(PACKAGE)" >> $(VERS_FILE)
	@echo "" >> $(VERS_FILE)
	@echo "const (" >> $(VERS_FILE)
	@echo "	Version = \"$(VERS)\"" >> $(VERS_FILE)
	@echo "	GitCommit = \"$(GIT_COMMIT)\" // the commit JUST BEFORE the release" >> $(VERS_FILE)
	@echo "	VersionDate = \"$(VERS_DATE)\" // UTC" >> $(VERS_FILE)
	@echo ")" >> $(VERS_FILE)
	@echo "" >> $(VERS_FILE)
	goimports -w $(VERS_FILE)
	/bin/cat $(VERS_FILE)
	git commit -am "$(VERS) release"
	git tag -a $(VERS) -m "$(VERS) release"
	git push
	git push origin --tags
