// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package main

const (
	Version     = "v0.4.11"
	GitCommit   = "182dc91"          // the commit JUST BEFORE the release
	VersionDate = "2026-06-04 18:50" // UTC
)
