// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package main

const (
	Version     = "v0.4.12"
	GitCommit   = "c14dc3a"          // the commit JUST BEFORE the release
	VersionDate = "2026-06-05 06:17" // UTC
)
